date: "{{ lookup('pipe', 'date +%m%d%Y_%H%M') }}"
app_env: "dev"
appname: "soft_api"
app_env_name: "{{ app_env }}_{{ appname }}"
wpDir: "/var/lib/jenkins/workspace/SOFT/APPS/DEV/DEV-SOFT-API/softAppCode/"
envfile: "/var/lib/jenkins/workspace/SOFT/APPS/DEV/DEV-SOFT-API/softAppCode"
appbuildpath: "/opt/app_builds/nodeapps"
appbuildDir: "/opt/app_builds/nodeapps/{{ app_env_name }}/"
# app_src_dir: "/var/lib/jenkins/workspace/DR_LambdaProject/APP_DEPLOYMENT/softAppCode/"
app_zip_file_name: "{{ date }}"
s3_bucket_name: "soft-d-apps-data"
lambda_fn_name: "soft-api"
aws_region: "ap-south-1"